version: '3.9'

services:

  rabbitmq:
    image: rabbitmq:3.10-rc-management-alpine
    command: rabbitmq-server
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 5s
      timeout: 15s
      retries: 3

  publisher:
    build:
      context: ./svc1
    ports:
      - "1111:1111"
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
  consumer:
    build:
      context: ./svc2
    ports:
      - "2222:2222"
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy